### ISSUE TITLE
Website API is slow when given irregular keyword

### ISSUE THREAD

**Issue by av3dj** [the-api-administration/coding-resources-api#45]
Searching easy keywords like "java", "css", ... are quick to get responses to. But, hard keywords like "veryhard", "supercalifragilisticexpialidocious", ... take a while to resolve to "Application Errror". The hard searches take around 1 minute to resolve.

**Comment by brianschnee** [comment]
Thank you for finding this

**Comment by Ethodeus** [comment]
Solved
