### ISSUE TITLE
Include "name" of resource in search results response

### ISSUE THREAD

**Issue by BrettCrafton** [the-api-administration/coding-resources-api#62]
At the moment, if you search for a resource on the landing page site via its "name", or part of its name, it does not get listed.

**Comment by brianschnee** [comment]
With the current version of our client-side app and API endpoint, we search through resources by keyword. We want a user to search for content based on a coding topic/technology/language. If a user has access to the resource by it's name, they would be able to find the resources URL via google.

Later versions of our API may include an endpoint for searches by name, however, we are going to close this issue for now.

Thank you

**Comment by BrettCrafton** [comment]
Thank you for the response. This is a fair point.
My recommendation was based on my original thought of when one kinda
knows/remembers the name, but not the exact name that would be needed to
search google. In most cases though, it would be searchable via the
client-side app via the keywords as someone familiar with the site should
know at least 1 keyword.
