### ISSUE TITLE
Make keywords collapsable

### ISSUE THREAD

**Issue by 20jasper** [the-api-administration/coding-resources-api#63]
Make the keywords collapsable 
We could do this with toggling truncation with css or with a details element in html

**Comment by brianschnee** [comment]
I like this feature. I think we should implement an option to expand the truncated text when a user clicks. This would allow us to apply the truncation to all the key value pairs in our resources objects and solve the styling issue for line wrapping inconsistencies.

**Comment by 20jasper** [comment]
fixed in pr #65
